// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dijital_asistan.Data;

#nullable disable

namespace dijital_asistan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250320120244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("dijital_asistan.Entities.Aksesuar", b =>
                {
                    b.Property<int>("AksesuarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AksesuarTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("KullanimDurumu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AksesuarId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Aksesuar");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Besin", b =>
                {
                    b.Property<int>("BesinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<float>("Karbonhidrat")
                        .HasColumnType("float");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<float>("Protein")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Yag")
                        .HasColumnType("float");

                    b.HasKey("BesinId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Besin");
                });

            modelBuilder.Entity("dijital_asistan.Entities.DegerTipi", b =>
                {
                    b.Property<int>("DegerTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DegerTipiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("DegerTipiId");

                    b.ToTable("DegerTipi");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Degerler", b =>
                {
                    b.Property<int>("DegerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DegerListesi")
                        .HasColumnType("longtext");

                    b.Property<int?>("DegerTipiId")
                        .HasColumnType("int");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("TahlilSonuclari")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DegerId");

                    b.HasIndex("DegerTipiId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Degerler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.HatirlaticiTipi", b =>
                {
                    b.Property<int>("HatirlaticiTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("HatirlaticiTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HatirlaticiTipiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("HatirlaticiTipiId");

                    b.ToTable("HatirlaticiTipi");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Hatirlaticilar", b =>
                {
                    b.Property<int>("HatirlaticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("HatirlaticiTipiId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("HatirlaticiId");

                    b.HasIndex("HatirlaticiTipiId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Hatirlaticilar");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Ilac", b =>
                {
                    b.Property<int>("IlacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AlindiMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("BaslangicTarih")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dozaj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IlacAd")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("IlacId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Ilaclar");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EpostaDogrulamaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EpostaDogrulandi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Yas")
                        .HasColumnType("int");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.RandevuTakip", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DoktorAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RandevuId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("RandevuTakipler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Rapor", b =>
                {
                    b.Property<int>("RaporId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("RaporIcerigi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("RaporTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RaporId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Rapor");
                });

            modelBuilder.Entity("dijital_asistan.Entities.SensorVeri", b =>
                {
                    b.Property<int>("SensorVeriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("SensorVeriTipiId")
                        .HasColumnType("int");

                    b.HasKey("SensorVeriId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SensorVeriTipiId");

                    b.ToTable("SensorVeri");
                });

            modelBuilder.Entity("dijital_asistan.Entities.SensorVeriTipi", b =>
                {
                    b.Property<int>("SensorVeriTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SensorTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Veri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SensorVeriTipiId");

                    b.ToTable("SensorVeriTipi");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Tavsiyeler", b =>
                {
                    b.Property<int>("TavsiyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TavsiyeMetni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TavsiyeId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Tavsiyeler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.YapayZekaAnaliz", b =>
                {
                    b.Property<int>("AnalizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnalizTipiId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("AnalizId");

                    b.HasIndex("AnalizTipiId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("YapayZekaAnaliz");
                });

            modelBuilder.Entity("dijital_asistan.Entities.YapayZekaAnalizTipi", b =>
                {
                    b.Property<int>("AnalizTipiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnalizTipiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("AnalizTipiId");

                    b.ToTable("YapayZekaAnalizTipi");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Aksesuar", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Aksesuarlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Besin", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Besinler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Degerler", b =>
                {
                    b.HasOne("dijital_asistan.Entities.DegerTipi", "DegerTipi")
                        .WithMany("Degerler")
                        .HasForeignKey("DegerTipiId");

                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Degerler")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("DegerTipi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Hatirlaticilar", b =>
                {
                    b.HasOne("dijital_asistan.Entities.HatirlaticiTipi", "HatirlaticiTipi")
                        .WithMany("Hatirlaticilar")
                        .HasForeignKey("HatirlaticiTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Hatirlaticilar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HatirlaticiTipi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Ilac", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.RandevuTakip", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Randevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Rapor", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Raporlar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.SensorVeri", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("SensorVerileri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dijital_asistan.Entities.SensorVeriTipi", "SensorVeriTipi")
                        .WithMany("SensorVeriler")
                        .HasForeignKey("SensorVeriTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("SensorVeriTipi");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Tavsiyeler", b =>
                {
                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("Tavsiyeler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.YapayZekaAnaliz", b =>
                {
                    b.HasOne("dijital_asistan.Entities.YapayZekaAnalizTipi", "AnalizTipi")
                        .WithMany("YapayZekaAnalizler")
                        .HasForeignKey("AnalizTipiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dijital_asistan.Entities.Kullanici", "Kullanici")
                        .WithMany("YapayZekaAnalizler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalizTipi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("dijital_asistan.Entities.DegerTipi", b =>
                {
                    b.Navigation("Degerler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.HatirlaticiTipi", b =>
                {
                    b.Navigation("Hatirlaticilar");
                });

            modelBuilder.Entity("dijital_asistan.Entities.Kullanici", b =>
                {
                    b.Navigation("Aksesuarlar");

                    b.Navigation("Besinler");

                    b.Navigation("Degerler");

                    b.Navigation("Hatirlaticilar");

                    b.Navigation("Randevular");

                    b.Navigation("Raporlar");

                    b.Navigation("SensorVerileri");

                    b.Navigation("Tavsiyeler");

                    b.Navigation("YapayZekaAnalizler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.SensorVeriTipi", b =>
                {
                    b.Navigation("SensorVeriler");
                });

            modelBuilder.Entity("dijital_asistan.Entities.YapayZekaAnalizTipi", b =>
                {
                    b.Navigation("YapayZekaAnalizler");
                });
#pragma warning restore 612, 618
        }
    }
}
